### ISSUE TITLE
Password is not saving

### ISSUE THREAD

**Issue by domidomsen** [MineAndCraft12/AaronOS#6] opened 2019-05-23 06:55 UTC
The os is writing in the USERFILES directory. But when i try to save the password , there is an error. "There was an issue setting your password. Try again.
QyFV`K_IgSgr00b#H^r7EyYcPBmUdv"

**Comment by MineAndCraft12** [comment] 2019-06-15 21:07
I'm working on a pretty big update right now that is making lots of changes to the code. Once this gets pushed, let's see if the issue is fixed in the update. It may be a while though.

If not, I'll look more closely into this and see what's going on.
Sorry I didn't see this sooner.

**Comment by MineAndCraft12** [comment] 2019-07-16 07:37
I pushed the Beta 1.0 update a couple days ago, is the issue still happening for you?

**Comment by MineAndCraft12** [comment] 2019-07-25 00:37
The issue is now fixed in B1.0.2.1

The issue is that the password was being set correctly, but aOS mistook it for an error. The issue is fixed.

**Closed as completed by MineAndCraft12** 2019-07-25 00:37 UTC
Labels: bug
